// Hard-coded NBA trivia quizzes for HoopQuiz

export const INITIAL_QUIZZES = [
  {
    id: 'ppg-25-2024',
    title: '25+ PPG Scorers (2023-24)',
    description: 'Name every player who averaged 25+ points per game in the 2023-24 regular season.',
    category: 'Scoring',
    difficulty: 'Medium',
    timeLimit: 300,
    answers: [
      'Joel Embiid',
      'Luka Doncic',
      'Giannis Antetokounmpo',
      'Shai Gilgeous-Alexander',
      'Jalen Brunson',
      'Kevin Durant',
      'Devin Booker',
      'Donovan Mitchell',
      'Kyrie Irving',
      'Anthony Edwards',
      'Trae Young',
      "De'Aaron Fox",
      'Jayson Tatum',
      'LeBron James',
      'Stephen Curry',
    ],
  },
  {
    id: 'celtics-2024-champs',
    title: '2024 NBA Champions Roster',
    description: 'Name the players on the Boston Celtics 2024 championship roster.',
    category: 'Teams',
    difficulty: 'Hard',
    timeLimit: 300,
    answers: [
      'Jayson Tatum',
      'Jaylen Brown',
      'Kristaps Porzingis',
      'Jrue Holiday',
      'Derrick White',
      'Al Horford',
      'Payton Pritchard',
      'Sam Hauser',
      'Luke Kornet',
      'Oshae Brissett',
      'Xavier Tillman',
      'Neemias Queta',
    ],
  },
  {
    id: 'all-time-scoring-top10',
    title: 'All-Time Scoring Leaders (Top 10)',
    description: 'Name the top 10 players on the NBA all-time regular season scoring list.',
    category: 'History',
    difficulty: 'Hard',
    timeLimit: 300,
    answers: [
      'LeBron James',
      'Kareem Abdul-Jabbar',
      'Karl Malone',
      'Kobe Bryant',
      'Michael Jordan',
      'Dirk Nowitzki',
      'Wilt Chamberlain',
      'Shaquille O\'Neal',
      'Carmelo Anthony',
      'Moses Malone',
    ],
  },
  {
    id: 'three-rings-2010s',
    title: 'Players with 3+ Titles in the 2010s',
    description: 'Name every player who won 3 or more NBA championships during the 2010s decade.',
    category: 'History',
    difficulty: 'Expert',
    timeLimit: 300,
    answers: [
      'LeBron James',
      'Stephen Curry',
      'Klay Thompson',
      'Draymond Green',
      'Andre Iguodala',
      'Shaun Livingston',
    ],
  },
  {
    id: 'all-nba-first-2024',
    title: '2024 All-NBA First Team',
    description: 'Name the 5 players selected to the All-NBA First Team for the 2023-24 season.',
    category: 'Awards',
    difficulty: 'Medium',
    timeLimit: 180,
    answers: [
      'Shai Gilgeous-Alexander',
      'Luka Doncic',
      'Giannis Antetokounmpo',
      'Jayson Tatum',
      'Nikola Jokic',
    ],
  },
]

// Common nicknames/abbreviations mapped to canonical full names,
// used to widen the fuzzy-match net beyond last names.
export const ALIASES = {
  sga: 'shai gilgeous-alexander',
  luka: 'luka doncic',
  doncic: 'luka doncic',
  giannis: 'giannis antetokounmpo',
  greekfreak: 'giannis antetokounmpo',
  lebron: 'lebron james',
  king: 'lebron james',
  kd: 'kevin durant',
  curry: 'stephen curry',
  steph: 'stephen curry',
  klay: 'klay thompson',
  jokic: 'nikola jokic',
  joker: 'nikola jokic',
  shaq: "shaquille o'neal",
  oneal: "shaquille o'neal",
  kareem: 'kareem abdul-jabbar',
  abduljabbar: 'kareem abdul-jabbar',
  kobe: 'kobe bryant',
  mj: 'michael jordan',
  jordan: 'michael jordan',
  dirk: 'dirk nowitzki',
  nowitzki: 'dirk nowitzki',
  melo: 'carmelo anthony',
  embiid: 'joel embiid',
  tatum: 'jayson tatum',
  brunson: 'jalen brunson',
  ad: 'anthony davis',
}
